name: GetX_Architecture
description: "A new Flutter project."

publish_to: 'none' 

version: 2.1.0

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.6
  hexcolor: ^3.0.1
  auto_size_text: ^3.0.0
  
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  get: ^4.6.6
  dio: ^5.7.0
  flutter_svg:
  get_storage: ^2.1.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dartz: ^0.10.1
  url_launcher: ^6.3.1
  change_app_package_name: ^1.4.0
  pinput: ^5.0.0
  image_picker: ^1.1.2
  mime_type: ^1.0.1
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.1.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/app_icon.png
   

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 600
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500

# Remove these fields from here; they belong in android and iOS config files
  # android:
  #   applicationId: "com.ngpstudio.ngpite"
  #   minSdkVersion: 16
  #   targetSdkVersion: 30
  #   compileSdkVersion: 30
  #   name: "NGPITE"
